const words = [
  { tier: 6, toHave: "Wisdom", toBe: "Wise", categories: ["W"] },
  { tier: 6, toHave: "Virtue", toBe: "Virtuous", categories: ["V"] },

  { tier: 6, toHave: "Connection", toBe: "Connected", categories: ["C", "V"] },
  {
    tier: 6,
    toHave: "Understanding",
    toBe: "Understanding",
    categories: ["U", "W"],
  },

  { tier: 5, toHave: "Equanimity", toBe: "Equanimous", categories: ["E"] },
  {
    tier: 5,
    toHave: "Acceptance",
    toBe: "Accepting",
    categories: ["C", "U", "E"],
  },
  { tier: 5, toHave: "Gratitude", toBe: "Grateful", categories: ["V", "G"] },
  { tier: 5, toHave: "Loving-kindness", categories: ["V", "C", "L"] },

  {
    tier: 4,
    toHave: "Mindfulness",
    toBe: "Mindful",
    categories: ["W", "U", "E", "A"],
  },
  {
    tier: 4,
    toHave: "Openness",
    toBe: "Open",
    categories: ["W", "U", "C", "E", "A"],
  },
  {
    tier: 4,
    toHave: "Open-mindedness",
    toBe: "Open-minded",
    categories: ["W", "U", "C", "E", "A"],
  },
  {
    tier: 4,
    toHave: "Curiosity",
    toBe: "Curious",
    categories: ["W", "U", "C", "E", "A"],
  },
  {
    tier: 4,
    toHave: "Presence",
    toBe: "Present",
    categories: ["W", "U", "C", "E", "A"],
  },
  {
    tier: 4,
    toHave: "Awareness",
    toBe: "Aware",
    categories: ["W", "U", "C", "E", "A"],
  },
  {
    tier: 4,
    toHave: "Attention",
    toBe: "Attentive",
    categories: ["W", "U", "C", "E", "A"],
  },
  {
    tier: 4,
    toHave: "Tranquility",
    toBe: "Tranquil",
    categories: ["W", "E", "A"],
  },
  { tier: 4, toHave: "Serenity", toBe: "Serene", categories: ["W", "E", "A"] },
  { tier: 4, toHave: "Calmness", toBe: "Calm", categories: ["W", "E", "A"] },
  {
    tier: 4,
    toHave: "Harmony",
    toBe: "Harmonious",
    categories: ["W", "E", "A", "C"],
  },
  {
    tier: 4,
    toHave: "Insight",
    toBe: "Insightful",
    categories: ["W", "U", "A"],
  },
  { tier: 4, toHave: "Love", toBe: "Loving", categories: ["V", "C", "L"] },
  { tier: 4, toHave: "Kindness", toBe: "Kind", categories: ["V", "C", "L"] },
  {
    tier: 4,
    toHave: "Compassion",
    toBe: "Compassionate",
    categories: ["V", "C", "L"],
  },
  {
    tier: 4,
    toHave: "Benevolence",
    toBe: "Benevolent",
    categories: ["V", "C", "L"],
  },
  {
    tier: 4,
    toHave: "Altruism",
    toBe: "Altruistic",
    categories: ["V", "C", "L"],
  },
  {
    tier: 4,
    toHave: "Resilience",
    toBe: "Resilient",
    categories: ["W", "E", "A"],
  },
  {
    tier: 4,
    toHave: "Appreciation",
    toBe: "Appreciative",
    categories: ["V", "G"],
  },
  { tier: 4, toHave: "Care", toBe: "Caring", categories: ["V", "C", "L"] },
  {
    tier: 4,
    toHave: "Generosity",
    toBe: "Generous",
    categories: ["V", "C", "L"],
  },
  {
    tier: 3,
    toHave: "Attunement",
    toBe: "Attuned",
    categories: ["C", "U", "E", "L"],
  },
  {
    tier: 3,
    toHave: "Observation",
    toBe: "Observant",
    categories: ["W", "U", "E", "A"],
  },
  {
    tier: 3,
    toHave: "Receptivity",
    toBe: "Receptive",
    categories: ["W", "C", "U", "E", "A"],
  },
  {
    tier: 3,
    toHave: "Intrigue",
    toBe: "Intrigued",
    categories: ["W", "C", "U", "L"],
  },
  {
    tier: 3,
    toHave: "Engagement",
    toBe: "Engaged",
    categories: ["W", "U", "C", "E"],
  },
  {
    tier: 3,
    toHave: "Humility",
    toBe: "Humble",
    categories: ["V", "W", "U", "E", "A"],
  },
  {
    tier: 3,
    toHave: "Empathy",
    toBe: "Empathetic",
    categories: ["V", "W", "C", "U", "E", "A", "L"],
  },
  { tier: 3, toHave: "Peace", toBe: "Peaceful", categories: ["W", "E", "A"] },
  { tier: 2, toHave: "Reason", toBe: "Reasonable", categories: ["W", "U"] },
  { tier: 2, toHave: "Rationality", toBe: "Rational", categories: ["W", "U"] },
  { tier: 2, toHave: "Logic", toBe: "Logical", categories: ["W", "U"] },
  { tier: 2, toHave: "Clarity", toBe: "Clear", categories: ["W", "U"] },
  { tier: 3, toHave: "Objectivity", toBe: "Objective", categories: ["W", "U"] },
  {
    tier: 3,
    toHave: "Respect",
    toBe: "Respectful",
    categories: ["V", "C", "L"],
  },
  {
    tier: 3,
    toHave: "Fondness",
    toBe: "Fond",
    categories: ["V", "C", "L", "G"],
  },
  {
    tier: 3,
    toHave: "Interest",
    toBe: "Interested",
    categories: ["W", "C", "U", "L"],
  },
  {
    tier: 3,
    toHave: "Magnanimity",
    toBe: "Magnanimous",
    categories: ["V", "W", "C", "U", "L"],
  },
  {
    tier: 3,
    toHave: "Charitability",
    toBe: "Charitable",
    categories: ["V", "W", "C", "U", "L"],
  },
  {
    tier: 3,
    toHave: "Supportiveness",
    toBe: "Supportive",
    categories: ["V", "C", "L"],
  },
  {
    tier: 2,
    toHave: "Trust",
    toBe: "Trusting",
    categories: ["V", "W", "C", "U", "E", "A", "L"],
  },
  {
    tier: 2,
    toHave: "Interconnectedness",
    toBe: "Interconnected",
    categories: ["V", "W", "C", "U", "L"],
  },
  {
    tier: 2,
    toHave: "Balance",
    toBe: "Balanced",
    categories: ["W", "U", "E", "A"],
  },
  {
    tier: 2,
    toHave: "Introspection",
    toBe: "Introspective",
    categories: ["W", "U", "E", "A"],
  },
  {
    tier: 1,
    toHave: "Exploration",
    toBe: "Exploratory",
    categories: ["W", "U", "E", "A"],
  },
  {
    tier: 2,
    toHave: "Fascination",
    toBe: "Fascinated",
    categories: ["W", "U", "G", "L"],
  },
  {
    tier: 2,
    toHave: "Reflection",
    toBe: "Reflective",
    categories: ["W", "U", "E", "A"],
  },
  {
    tier: 2,
    toHave: "Encouragement",
    toBe: "Encouraging",
    categories: ["V", "C", "L"],
  },
  {
    tier: 2,
    toHave: "Affirmation",
    toBe: "Affirming",
    categories: ["V", "C", "L"],
  },
  {
    tier: 2,
    toHave: "Reliability",
    toBe: "Reliable",
    categories: ["V", "C", "L"],
  },
  {
    tier: 2,
    toHave: "Consistency",
    toBe: "Consistent",
    categories: ["V", "C", "L"],
  },
  {
    tier: 2,
    toHave: "Dependability",
    toBe: "Dependable",
    categories: ["V", "C", "L"],
  },
  {
    tier: 2,
    toHave: "Authenticity",
    toBe: "Authentic",
    categories: ["V", "C", "U", "E"],
  },
  { tier: 2, toHave: "Joy", toBe: "Joyful", categories: ["V", "C", "G", "L"] },
  {
    tier: 2,
    toHave: "Lightness",
    toBe: "Light",
    categories: ["V", "E", "G", "L"],
  },
  {
    tier: 2,
    toHave: "Humor",
    toBe: "Humorous",
    categories: ["V", "W", "E", "L"],
  },
  {
    tier: 2,
    toHave: "Honesty",
    toBe: "Honest",
    categories: ["V", "C", "E", "L"],
  },
  {
    tier: 2,
    toHave: "Forgiveness",
    toBe: "Forgiving",
    categories: ["V", "C", "A", "L"],
  },
  {
    tier: 2,
    toHave: "Intentionality",
    toBe: "Intentional",
    categories: ["W", "U", "E", "A"],
  },
  {
    tier: 2,
    toHave: "Concentration",
    toBe: "Concentrated",
    categories: ["W", "E", "U"],
  },
  {
    tier: 2,
    toHave: "Inquisitiveness",
    toBe: "Inquisitive",
    categories: ["W", "U", "A", "L"],
  },
  {
    tier: 2,
    toHave: "Enthusiasm",
    toBe: "Enthusiastic",
    categories: ["V", "C", "L"],
  },
  {
    tier: 2,
    toHave: "Perception",
    toBe: "Perceptive",
    categories: ["W", "U", "E"],
  },
  {
    tier: 2,
    toHave: "Consideration",
    toBe: "Considerate",
    categories: ["V", "W", "C", "U", "E", "L"],
  },
  {
    tier: 2,
    toHave: "Thankfulness",
    toBe: "Thankful",
    categories: ["V", "G", "C", "L"],
  },
  {
    tier: 2,
    toHave: "Positivity",
    toBe: "Positive",
    categories: ["V", "E", "G", "L"],
  },
  {
    tier: 2,
    toHave: "Playfulness",
    toBe: "Playful",
    categories: ["V", "C", "L"],
  },
  {
    tier: 2,
    toHave: "Communication",
    toBe: "Communicative",
    categories: ["V", "C", "L"],
  },
  {
    tier: 2,
    toHave: "Responsiveness",
    toBe: "Responsive",
    categories: ["V", "C", "L"],
  },
  {
    tier: 2,
    toHave: "Expression",
    toBe: "Expressive",
    categories: ["V", "C", "L"],
  },
  { tier: 2, toHave: "Fairness", toBe: "Fair", categories: ["V", "C", "L"] },
  { tier: 2, toHave: "Stability", toBe: "Stable", categories: ["W", "E", "A"] },
  {
    tier: 2,
    toHave: "Immersion",
    toBe: "Immersed",
    categories: ["W", "C", "E"],
  },
  {
    tier: 2,
    toHave: "Collaboration",
    toBe: "Collaborative",
    categories: ["V", "C", "L"],
  },
  {
    tier: 2,
    toHave: "Support",
    toBe: "Supportive",
    categories: ["V", "C", "L"],
  },
  {
    tier: 2,
    toHave: "Celebration",
    toBe: "Celebratory",
    categories: ["V", "C", "G", "L"],
  },
  { tier: 2, toHave: "Play", toBe: "Playful", categories: ["V", "C", "L"] },
  { tier: 2, toHave: "Creativity", toBe: "Creative", categories: ["W", "U"] },
  {
    tier: 2,
    toHave: "Composition",
    toBe: "Composed",
    categories: ["W", "E", "A"],
  },
  { tier: 2, toHave: "Evenness", toBe: "Even", categories: ["W", "E", "A"] },
  {
    tier: 2,
    toHave: "Steadiness",
    toBe: "Steady",
    categories: ["W", "E", "A"],
  },
  {
    tier: 2,
    toHave: "Thoughtfulness",
    toBe: "Thoughtful",
    categories: ["V", "W", "C", "U", "L"],
  },
  { tier: 2, toHave: "Focus", toBe: "Focused", categories: ["W", "E", "A"] },
  { tier: 2, toHave: "Ease", toBe: "Eased", categories: ["W", "E", "A"] },
  {
    tier: 2,
    toHave: "Adaptability",
    toBe: "Adaptable",
    categories: ["W", "E", "A", "U"],
  },
  {
    tier: 2,
    toHave: "Flexibility",
    toBe: "Flexible",
    categories: ["W", "E", "A"],
  },
  {
    tier: 2,
    toHave: "Cooperation",
    toBe: "Cooperative",
    categories: ["V", "C", "E", "L"],
  },
  {
    tier: 2,
    toHave: "Regulation",
    toBe: "Regulated",
    categories: ["W", "E", "A"],
  },
  {
    tier: 2,
    toHave: "Concern",
    toBe: "Concerned",
    categories: ["V", "C", "U", "L"],
  },
  {
    tier: 2,
    toHave: "Delight",
    toBe: "Delighted",
    categories: ["V", "C", "G"],
  },
  { tier: 2, toHave: "Warmth", toBe: "Warm", categories: ["V", "C", "L"] },
  {
    tier: 2,
    toHave: "Genuineness",
    toBe: "Genuine",
    categories: ["V", "C", "L"],
  },
  { tier: 2, toHave: "Patience", toBe: "Patient", categories: ["W", "E", "A"] },
  {
    tier: 2,
    toHave: "Discernment",
    toBe: "Discerning",
    categories: ["W", "U", "E"],
  },
  {
    tier: 2,
    toHave: "Sincerity",
    toBe: "Sincere",
    categories: ["V", "C", "L"],
  },
  {
    tier: 2,
    toHave: "Courtesy",
    toBe: "Courteous",
    categories: ["V", "C", "L"],
  },
  { tier: 2, toHave: "Tact", toBe: "Tactful", categories: ["V", "C", "L"] },
  {
    tier: 2,
    toHave: "Gentleness",
    toBe: "Gentle",
    categories: ["V", "C", "L", "E"],
  },
  { tier: 2, toHave: "Zest", toBe: "Zestful", categories: ["V", "C", "L"] },
  {
    tier: 2,
    toHave: "Friendliness",
    toBe: "Friendly",
    categories: ["V", "C", "L"],
  },
  {
    tier: 2,
    toHave: "Cheerfulness",
    toBe: "Cheerful",
    categories: ["V", "C", "L", "G"],
  },
  {
    tier: 2,
    toHave: "Contemplation",
    toBe: "Contemplative",
    categories: ["W", "U", "E"],
  },
  {
    tier: 2,
    toHave: "Contentment",
    toBe: "Content",
    categories: ["V", "G", "E", "A"],
  },
  {
    tier: 2,
    toHave: "Earnestness",
    toBe: "Earnest",
    categories: ["V", "C", "L"],
  },
  {
    tier: 2,
    toHave: "Excitement",
    toBe: "Excited",
    categories: ["V", "C", "L"],
  },
  {
    tier: 2,
    toHave: "Helpfulness",
    toBe: "Helpful",
    categories: ["V", "C", "L"],
  },
  {
    tier: 2,
    toHave: "Hospitality",
    toBe: "Hospitable",
    categories: ["V", "C", "L"],
  },
  {
    tier: 2,
    toHave: "Inspiration",
    toBe: "Inspired",
    categories: ["V", "G", "C"],
  },
  {
    tier: 1,
    toHave: "Thoroughness",
    toBe: "Thorough",
    categories: ["W", "U", "E"],
  },
  {
    tier: 1,
    toHave: "Coherence",
    toBe: "Coherent",
    categories: ["W", "U", "E"],
  },
  {
    tier: 1,
    toHave: "Generativity",
    toBe: "Generative",
    categories: ["V", "C", "L"],
  },
  {
    tier: 1,
    toHave: "Inclusivity",
    toBe: "Inclusive",
    categories: ["V", "C", "L"],
  },
  {
    tier: 1,
    toHave: "Temperance",
    toBe: "Temperate",
    categories: ["W", "U", "E", "A"],
  },
  {
    tier: 1,
    toHave: "Prudence",
    toBe: "Prudent",
    categories: ["W", "U", "E", "A"],
  },
  {
    tier: 1,
    toHave: "Ambition",
    toBe: "Ambitious",
    categories: ["V", "C", "L"],
  },
  {
    tier: 1,
    toHave: "Motivation",
    toBe: "Motivated",
    categories: ["V", "C", "L"],
  },
  { tier: 1, toHave: "Drive", toBe: "Driven", categories: ["V", "C", "L"] },
  { tier: 1, toHave: "Confidence", toBe: "Confident", categories: ["W", "E"] },
  { tier: 1, toHave: "Courage", toBe: "Courageous", categories: ["W", "E"] },
  { tier: 1, toHave: "Bravery", toBe: "Brave", categories: ["W", "E"] },
  { tier: 1, toHave: "Strength", toBe: "Strong", categories: ["W", "E"] },
  {
    tier: 1,
    toHave: "Diligence",
    toBe: "Diligent",
    categories: ["V", "E", "L"],
  },
  {
    tier: 1,
    toHave: "Happiness",
    toBe: "Happy",
    categories: ["V", "C", "G", "E"],
  },
  {
    tier: 1,
    toHave: "Nurturance",
    toBe: "Nurturing",
    categories: ["V", "C", "L"],
  },
  {
    tier: 1,
    toHave: "Optimism",
    toBe: "Optimistic",
    categories: ["V", "W", "E", "A", "U"],
  },
  {
    tier: 1,
    toHave: "Integrity",
    toBe: "Integrous",
    categories: ["V", "C", "L"],
  },
  {
    tier: 1,
    toHave: "Levity",
    toBe: "Lighthearted",
    categories: ["V", "C", "L", "E"],
  },
  {
    tier: 1,
    toHave: "Enjoyment",
    toBe: "Joyous",
    categories: ["V", "C", "G", "L"],
  },
];
const tiers = [6, 5, 4, 3, 2, 1];
const categories = {
  V: "Virtue",
  W: "Wisdom",
  C: "Connection",
  U: "Understanding",
  E: "Equanimity",
  A: "Acceptance",
  G: "Gratitude",
  L: "Loving-kindness",
};
